# Generated by Django 5.1.5 on 2025-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0002_userprofile_address_userprofile_alternate_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="year_of_joining",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="year_of_experience",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
