# Generated by Django 5.1.5 on 2025-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0005_land"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="land",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="land",
            name="description",
        ),
        migrations.RemoveField(
            model_name="land",
            name="image",
        ),
        migrations.RemoveField(
            model_name="land",
            name="land_paper",
        ),
        migrations.RemoveField(
            model_name="land",
            name="location",
        ),
        migrations.RemoveField(
            model_name="land",
            name="size",
        ),
        migrations.RemoveField(
            model_name="land",
            name="status",
        ),
        migrations.AddField(
            model_name="land",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="irrigation_facilities",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="istrict",
            field=models.CharField(default="Default District", max_length=255),
        ),
        migrations.AddField(
            model_name="land",
            name="ownership_document",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="land",
            name="previous_crop",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="recent_photos",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="land",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="survey_document",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="land",
            name="survey_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="total_area",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
