# Generated by Django 5.1.5 on 2025-02-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0006_remove_land_created_at_remove_land_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="land",
            old_name="istrict",
            new_name="district",
        ),
        migrations.AddField(
            model_name="land",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
