# Generated by Django 5.1.5 on 2025-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
