# Generated by Django 5.1.5 on 2025-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
