# Generated by Django 5.1.5 on 2025-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0010_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
