# Generated by Django 5.1.5 on 2025-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0011_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="current_state",
            field=models.CharField(
                choices=[("free", "Free"), ("occupied", "Occupied")],
                default="free",
                max_length=10,
            ),
        ),
    ]
