# Generated by Django 5.1.5 on 2025-02-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0013_landassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
