# Generated by Django 5.1.4 on 2025-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACP", "0015_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("job", "Job Assignment"),
                    ("course", "New Course"),
                    ("general", "General Update"),
                    ("workcompleted", "Workcompleted"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("worker", "Agricultural Worker"),
                    ("provider", "Land Provider"),
                    ("buyer", "Buyer"),
                    ("student", "Student"),
                ],
                max_length=20,
            ),
        ),
    ]
